### ISSUE TITLE
Unable to run redux-cli, issue with finding particular modules?

### ISSUE THREAD

**Issue by deep-c** [SpencerCDixon/redux-cli#54]
Hi,

Not sure if this is just an issue with me but i cant seem to run any redux commands other than `redux` which obviously just shows what is available. I get the following:

```
deepc@DESKTOP-M6C5NC2 MINGW64 /d/Projects/vagrant_local/docker/node/app2
$ redux help generate
module.js:339
    throw err;
    ^

Error: Cannot find module 'C:\Users\deepc\AppData\Roaming\npm\node_modules\redux-cli\bin\index-generate'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

deepc@DESKTOP-M6C5NC2 MINGW64 /d/Projects/vagrant_local/docker/node/app2
$ redux g smart Button
module.js:339
    throw err;
    ^

Error: Cannot find module 'C:\Users\deepc\AppData\Roaming\npm\node_modules\redux-cli\bin\index-g'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

```

Im running node v 4.2.2 on windows 10. I installed it globally and am trying to use it with React Redux Starter Kit. 

Thanks

**Comment by SpencerCDixon** [comment]
Interesting, don't have a windows machine to test this.  I'll download a VM and see if I can debug

**Comment by amborle** [comment]
Can confirm on my Windows machine as well.

**Comment by CurtisHumphrey** [comment]
It has something to do with out the options are being passed. I can get it to say index-g or index-generate depending on what I type

**Comment by CurtisHumphrey** [comment]
ok I can get it to work if the command is redux-g or redux-generate

**Comment by ichengyc** [comment]
i have same problem on window_7_x64, node version: v5.9.0, npm version: 3.7.3. 
detail error message(see  below):

module.js:341
    throw err;
    ^

Error: Cannot find module 'C:\Users\q\AppData\Roaming\npm\node_modules\redux-cli\bin\index-generate'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

**Comment by blairbodnar** [comment]
Also happening for me on Windows 10 x64 with node v5.9.1. And like @CurtisHumphrey mentioned, seems to be something with the options. redux-g with no space works.

**Comment by Medros** [comment]
I have a similar issue myself running any commands. Cannot find module x

`$ redux init
module.js:341
    throw err;
    ^

Error: Cannot find module 'U:\Users\Junior.Stormrage\AppData\Roaming\npm\node_modules\redux-cli\bin\index-init'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
`

This is the same if I try to generate a new project or update existing.

**Comment by Medros** [comment]
Here's the same when I try a new project. 

I've gone to the path and there are files present however they are named redux-init and redux-new. There is no index-init or index-new

Also on Windows 10 node v5.9.0
```
$ redux new soundboard-redux -H
module.js:341
    throw err;
    ^

Error: Cannot find module 'U:\Users\Junior.Stormrage\AppData\Roaming\npm\node_modules\redux-cli\bin\index-new'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
```

**Comment by anakinjay** [comment]
Exact same issues for me on windows 10.

**Comment by waniwang** [comment]
Got the same problem...

**Comment by a0ly** [comment]
$ redux g form loginForm
module.js:327
    throw err;
    ^

Error: Cannot find module 'C:\Users\being\AppData\Roaming\npm\node_modules\redux-cli\bin\ind                   ex-g'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

Also at windows7, Node 4.4.1

**Comment by AnhHT** [comment]
For windows user:
redux redux-g/i/ xyz

**Comment by danyx23** [comment]
Same problem, Win 10 4.4.2.

Anything we can do to help debug this? Would be neat to be able to use redux-cli :)

**Comment by deep-c** [comment]
@danyx23 Hi, as others have found you can use `redux-g` instead of `redux g` on windows.

**Comment by danyx23** [comment]
@deep-c thank you! But this doesn't work to create a new project, does it? That is what I wanted to do when I landed here :). But good to know that the rest of redux-cli should work with redux-g.

**Comment by augusto-altman** [comment]
I have the same problem when trying to create a new project.

Windows 8.1, Node v5.x

**Comment by augusto-altman** [comment]
For those that are dealing with _new_ and _init_ issues on Windows, try using _redux-init_ instead of _redux init_ and _redux-new_ instead of _redux new_

**Comment by danyx23** [comment]
When running redux-new I get: (Win10, powershell, git available via git for windows)
```
λ redux-new test
COMMAND:  undefined
  info: Creating new directory...
  create: Created directory: test
  info: Setting up tracking with git...
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:856:11)
    at ReadStream.Socket._writeGeneric (net.js:675:26)
    at ReadStream.Socket._write (net.js:694:8)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at ReadStream.Writable.write (_stream_writable.js:207:11)
    at ReadStream.Socket.write (net.js:620:40)
    at render (C:\Users\Daniel\AppData\Roaming\npm\node_modules\redux-cli\node_modules\log-update\index.js:11:10)
    at null._repeat (C:\Users\Daniel\AppData\Roaming\npm\node_modules\redux-cli\lib\models\ui.js:118:11)
    at wrapper [as _onTimeout] (timers.js:275:11)
 D:\projects\code\douglasconnect
```

**Comment by devneel** [comment]
Having this issue as well. 
`redux new popcircle
module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\devneel\AppData\Roaming\npm\node_modules\redux-cli\bin\index-new'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
`

and trying redux-new popcircle results in:

**Comment by mzvast** [comment]
Windows 10 X64 same when $ redux-new cli-redux

COMMAND:  undefined
  info: Creating new directory...
  create: Created directory: cli-redux
  info: Setting up tracking with git...
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:890:11)
    at ReadStream.Socket._writeGeneric (net.js:679:26)
    at ReadStream.Socket._write (net.js:698:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at ReadStream.Writable.write (_stream_writable.js:215:11)
    at ReadStream.Socket.write (net.js:624:40)
    at render (C:\Users\mzvast\AppData\Roaming\npm\node_modules\redux-cli\node_modules\log-update\index.js:11:10)
    at Timeout._repeat (C:\Users\mzvast\AppData\Roaming\npm\node_modules\redux-cli\lib\models\ui.js:118:11)
    at Timeout.wrapper [as _onTimeout] (timers.js:408:11)

**Comment by ramonmata** [comment]
Same error here 

, Windows 10

```
λ redux-new demoApp                                                                                                  
COMMAND:  undefined                                                                                                  
  info: Creating new directory...                                                                                    
  create: Created directory: demoApp                                                                                 
  info: Setting up tracking with git...                                                                              
events.js:154                                                                                                        
      throw er; // Unhandled 'error' event                                                                           
      ^                                                                                                              
                                                                                                                     
Error: write EPIPE                                                                                                   
    at exports._errnoException (util.js:890:11)                                                                      
    at ReadStream.Socket._writeGeneric (net.js:679:26)                                                               
    at ReadStream.Socket._write (net.js:698:8)                                                                       
    at doWrite (_stream_writable.js:301:12)                                                                          
    at writeOrBuffer (_stream_writable.js:287:5)                                                                     
    at ReadStream.Writable.write (_stream_writable.js:215:11)                                                        
    at ReadStream.Socket.write (net.js:624:40)                                                                       
    at render (C:\Users\ramon.mata\AppData\Roaming\npm\node_modules\redux-cli\node_modules\log-update\index.js:11:10)
    at Timeout._repeat (C:\Users\ramon.mata\AppData\Roaming\npm\node_modules\redux-cli\lib\models\ui.js:118:11)      
    at Timeout.wrapper [as _onTimeout] (timers.js:408:11)                                                            
```

**Comment by mmichaels01** [comment]
Just submitted pull request that should fix issue with redux-new

https://github.com/SpencerCDixon/redux-cli/pull/65

**Comment by tornewuff** [comment]
#67 makes "redux new" etc work, without having to directly invoke the subcommands.
