### ISSUE TITLE
Generator fails: Syntax Error

### ISSUE THREAD

**Issue by woniesong92** [SpencerCDixon/redux-cli#59]
I ran the following commands.

```
$ redux new practice-redux-container
$ cd practice-redux-container
$ redux g smart hello
$ redux g dumb hi
```

Did I forget to configure something?

```
/usr/local/lib/node_modules/redux-cli/node_modules/jsonfile/index.js:38
      throw err
            ^
SyntaxError: practice-redux-container/.reduxrc: Unexpected token u
    at Object.parse (native)
    at Object.readFileSync (/usr/local/lib/node_modules/redux-cli/node_modules/jsonfile/index.js:34:17)
    at ProjectSettings.loadSettings (/usr/local/lib/node_modules/redux-cli/lib/models/project-settings.js:45:44)
    at new ProjectSettings (/usr/local/lib/node_modules/redux-cli/lib/models/project-settings.js:38:10)
    at Generate.SubCommand (/usr/local/lib/node_modules/redux-cli/lib/models/sub-command.js:28:41)
    at new Generate (/usr/local/lib/node_modules/redux-cli/lib/sub-commands/generate.js:45:82)
    at Object.<anonymous> (/usr/local/lib/node_modules/redux-cli/lib/cli/redux-generate.js:19:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

$ redux g dumb hi
/usr/local/lib/node_modules/redux-cli/node_modules/jsonfile/index.js:38
      throw err
            ^
SyntaxError: practice-redux-container/.reduxrc: Unexpected token u
    at Object.parse (native)
    at Object.readFileSync (/usr/local/lib/node_modules/redux-cli/node_modules/jsonfile/index.js:34:17)
    at ProjectSettings.loadSettings (/usr/local/lib/node_modules/redux-cli/lib/models/project-settings.js:45:44)
    at new ProjectSettings (/usr/local/lib/node_modules/redux-cli/lib/models/project-settings.js:38:10)
    at Generate.SubCommand (/usr/local/lib/node_modules/redux-cli/lib/models/sub-command.js:28:41)
    at new Generate (/usr/local/lib/node_modules/redux-cli/lib/sub-commands/generate.js:45:82)
    at Object.<anonymous> (/usr/local/lib/node_modules/redux-cli/lib/cli/redux-generate.js:19:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by BobWhitelock** [comment]
I believe I've run into a similar issue. Have you run `redux init` yet? What's the contents of `.reduxrc` in your project directory?

I encountered a similar error when I hit ctrl-C after running `redux init`, and then `.reduxrc` was created containing just `undefined`, which then causes `redux g` to fail.

**Comment by woniesong92** [comment]
Ah, so this is what happened. After a fresh install generators failed with a different error message:

```
$ redux g smart hello
2practice/blueprints/smart/index.js:2
  description () {
              ^
SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Function.load (/usr/local/lib/node_modules/redux-cli/lib/models/blueprint.js:330:33)
    at Function.lookup (/usr/local/lib/node_modules/redux-cli/lib/models/blueprint.js:311:28)
    at _class.lookupBlueprint (/usr/local/lib/node_modules/redux-cli/lib/tasks/generate-from-blueprint.js:69:34)
```

In order to fix it, I ran `redux init` and never finished it. Then you are left with an empty `reduxrc`. So the real error message is the one above.

**Comment by SpencerCDixon** [comment]
I'm not experiencing this behavior on the latest release.  Are you using v1.4 >?
