### ISSUE TITLE
Problem with `redux g` alias

### ISSUE THREAD

**Issue by pustovalov** [SpencerCDixon/redux-cli#95]
```
Pavel:spa_frontend pavel$ redux generate dumb test
  info: installing blueprint...
  create: /Users/pavel/spa_frontend/src/components/test.js
  create: /Users/pavel/spa_frontend/tests/components/test.test.js
  info: finished installing blueprint.
Pavel:spa_frontend pavel$ redux g dumb testt
module.js:472
    throw err;
    ^

'rror: Cannot find module '/Users/pavel/spa_frontend/
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
Pavel:spa_frontend pavel$
```

version: 1.8.0
OS: macOS 10.12.2

**Comment by pustovalov** [comment]
It's helped me, change this line:

bin/redux-g.js:
```
require('./redux-generate.js');
```

to:
```
require('../lib/cli/redux-generate');
```

**Comment by pustovalov** [comment]
https://github.com/SpencerCDixon/redux-cli/commit/fb987e8478a094d761f76a1d4918229cc23664bb
