### ISSUE TITLE
when i run 'npm run start',the cli throw these errors:

### ISSUE THREAD

**Issue by arixse** [SpencerCDixon/redux-cli#97]
os:windows 10
nodejs:v6.11.0
npm:v3.10.10
webpack:v2.6.1

when i run 'npm run start',the cli throw these errors:

>react-redux-starter-kit@3.0.1 start D:\redux-cli-test
>cross-env NODE_ENV=development node build/scripts/start

i Starting server...
i Enabling webpack development and HMR middleware
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at EventEmitter.listen (D:\redux-cli-test\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (D:\redux-cli-test\build\scripts\start.js:4:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter-kit@3.0.1 start: `cross-env NODE_ENV=development node build/scripts/start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-redux-starter-kit@3.0.1 start script 'cross-env NODE_ENV=development node build/scripts/start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-redux-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node build/scripts/start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-redux-starter-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-redux-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\redux-cli-test\npm-debug.log

**Comment by benrampon** [comment]
Do you not already have an App running on the port 3000 ?

**Comment by arixse** [comment]
yes,i forgot,thanks!
